"""
Generates src/shop.ts from Discord's own Shop data.

Infinitay/discord-collectibles-archive keeps Discord's collectibles catalogue
committed as JSON: every collection with its summary, its gradient colours and
its products, and every product with the price Discord charges and the reduced
price it charges Nitro subscribers. That is where the Shop's names, copy and
prices come from, rather than being made up.

Only the four collections whose avatar decorations are vendored by
tools/fetch-decorations.py are emitted, so every item on the Shop page has its
real artwork behind it.

    python3 tools/fetch-shop.py
"""
import json
import os
import urllib.request

BASE = 'https://raw.githubusercontent.com/Infinitay/discord-collectibles-archive/main/discord-data/collections'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src/shop.ts')

# the collections whose decorations we hold art for
SLUGS = ['elements', 'galaxy', 'lofi-vibes', 'lunar-new-year']

# Discord's product and item type numbers
DECORATION, EFFECT, BUNDLE = 0, 1, 1000
# price keys: 0 is the list price, 4 the price a Nitro subscriber pays
LIST, NITRO = '0', '4'


def slug(name: str) -> str:
    return name.lower().replace("'", '').replace(' ', '-')


def price(product: dict, key: str):
    try:
        return product['prices'][key]['country_prices']['prices'][0]['amount'] / 100
    except (KeyError, IndexError):
        return None


def hexc(n: int) -> str:
    return '#%06x' % n


def main() -> None:
    have = {
        d['id']
        for d in json.load(open(os.path.join(ROOT, 'src/assets/decorations/index.json')))
    }
    collections = []
    for s in SLUGS:
        with urllib.request.urlopen(f'{BASE}/{s}.json', timeout=60) as r:
            d = json.load(r)
        bundles, decorations, effects = [], [], []
        for p in d['products']:
            entry = {
                'id': slug(p['name']),
                'name': p['name'],
                'summary': p['summary'],
                'price': price(p, LIST),
                'nitro': price(p, NITRO),
            }
            if p['type'] == BUNDLE:
                entry['items'] = [b['name'] for b in p.get('bundled_products', [])]
                bundles.append(entry)
            elif p['type'] == DECORATION:
                if entry['id'] not in have:
                    print(f'  ! no art for {p["name"]}, skipped')
                    continue
                decorations.append(entry)
            elif p['type'] == EFFECT:
                effects.append(entry)
        collections.append({
            'id': s,
            'name': d['name'],
            'summary': d['summary'],
            'colors': [hexc(c) for c in d['styles']['background_colors']],
            'button': hexc(d['styles']['button_colors'][0]),
            'bundles': bundles,
            'decorations': decorations,
            'effects': effects,
        })
        print(
            f'{d["name"]:16} {len(decorations)} decorations, '
            f'{len(effects)} effects, {len(bundles)} bundle(s)'
        )

    body = json.dumps(collections, indent=2)
    with open(OUT, 'w') as f:
        f.write(
            '''/**
 * The Shop's catalogue — Discord's own.
 *
 * Generated by tools/fetch-shop.py from Infinitay/discord-collectibles-archive,
 * which keeps Discord's collectibles catalogue committed as JSON. The
 * collection names and summaries, the bundle and item names, the gradient
 * colours and both prices — what Discord charges, and the lower price it
 * charges a Nitro subscriber — are all theirs.
 *
 * Only the collections whose avatar decorations are vendored under
 * src/assets/decorations are here, so nothing on the page is a name without
 * art behind it. Profile effects are listed with their real names but have no
 * artwork: those are rendered from Discord's CDN, which is unreachable here.
 *
 * Do not edit — run the tool.
 */

export type ShopProduct = {
  id: string
  name: string
  summary: string
  /** USD, as Discord lists it */
  price: number | null
  /** USD, the reduced price a Nitro subscriber pays */
  nitro: number | null
  /** bundles only: the products inside */
  items?: string[]
}

export type ShopCollection = {
  id: string
  name: string
  summary: string
  /** the collection's own gradient, from Discord's style block */
  colors: string[]
  button: string
  bundles: ShopProduct[]
  decorations: ShopProduct[]
  effects: ShopProduct[]
}

export const COLLECTIONS: ShopCollection[] = '''
            + body
            + '\n\nexport const money = (n: number) => `$${n.toFixed(2)}`\n'
        )
    print(f'\n-> {OUT}')


if __name__ == '__main__':
    main()
