"""
Vendors the typefaces Discord letters a display name in.

Nitro's display-name styles pick a font, an effect and a colour. The font list
is the client's own `DisplayNameFont` enum, and all but two of the faces it
ships are Google Fonts, which the google/fonts repository carries under the
OFL — reachable here where fonts.gstatic.com is not.

Neo Castel and Sinistre are the exceptions: Discord licensed those, they are on
no public mirror, and inventing a lookalike would be worse than leaving them
out. Everything else is the real typeface.

Each face is subset to the characters a display name can hold — Latin, digits,
the punctuation Discord allows — and written as WOFF2, which takes a 300KB
variable font down to a few kilobytes.

    python3 tools/fetch-name-fonts.py
"""
import io
import os
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src/assets/namefonts')
GOOGLE = 'https://raw.githubusercontent.com/google/fonts/main'

# the client's own DisplayNameFont ids, and where the face lives
FONTS: dict[str, tuple[int, str, str]] = {
    #  slug          id   file                                          family
    'cherry-bomb': (3, 'ofl/cherrybombone/CherryBombOne-Regular.ttf', 'Cherry Bomb One'),
    'chicle': (4, 'ofl/chicle/Chicle-Regular.ttf', 'Chicle'),
    'museo-moderno': (6, 'ofl/museomoderno/MuseoModerno%5Bwght%5D.ttf', 'MuseoModerno'),
    'pixelify': (8, 'ofl/pixelifysans/PixelifySans%5Bwght%5D.ttf', 'Pixelify Sans'),
    'zilla-slab': (12, 'ofl/zillaslab/ZillaSlab-Bold.ttf', 'Zilla Slab'),
    'playpen-sans': (13, 'ofl/playpensans/PlaypenSans%5Bwght%5D.ttf', 'Playpen Sans'),
    'orbitron': (14, 'ofl/orbitron/Orbitron%5Bwght%5D.ttf', 'Orbitron'),
    'new-rocker': (15, 'ofl/newrocker/NewRocker-Regular.ttf', 'New Rocker'),
    'kalam': (16, 'ofl/kalam/Kalam-Bold.ttf', 'Kalam'),
}

# what a display name can contain: Discord allows letters, digits, spaces and a
# short list of punctuation, so the subset is that and nothing else
CHARS = (
    'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    'abcdefghijklmnopqrstuvwxyz'
    '0123456789'
    " .,'’-_!?&+*#@$%()[]{}/\\:;\"~^|<>=`"
)


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    total = 0
    for slug, (fid, path, family) in FONTS.items():
        with urllib.request.urlopen(f'{GOOGLE}/{path}', timeout=90) as r:
            raw = r.read()
        font = TTFont(io.BytesIO(raw))
        # a variable face carries every weight on its axis; a display name is
        # drawn at one, so pin it before subsetting or the axis dominates the
        # file (Playpen Sans is 161KB with it, 20KB without)
        if 'fvar' in font:
            axes = {a.axisTag: a for a in font['fvar'].axes}
            if 'wght' in axes:
                target = min(700, axes['wght'].maxValue)
                font = instancer.instantiateVariableFont(font, {'wght': target})
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.desubroutinize = True
        # a variable font is pinned to the weight the name is drawn at, which
        # is far smaller than carrying the whole axis
        opts.layout_features = ['*']
        s = subset.Subsetter(options=opts)
        s.populate(text=CHARS)
        s.subset(font)
        out = os.path.join(OUT, f'{slug}.woff2')
        font.flavor = 'woff2'
        font.save(out)
        size = os.path.getsize(out)
        total += size
        print(f'{slug:14} id {fid:<3} {family:16} {len(raw) // 1024:4}KB -> {size // 1024}KB')
    # the @font-face rules, and the list the picker reads
    css = [
        '/*',
        ' * The typefaces Discord letters a display name in. Generated by',
        ' * tools/fetch-name-fonts.py — edit that, not this.',
        ' *',
        ' * Each is the real face out of google/fonts under the OFL, subset to the',
        ' * characters a display name can hold and pinned to one weight.',
        ' */',
        '',
    ]
    for slug, (_fid, _path, family) in FONTS.items():
        css += [
            '@font-face {',
            f"  font-family: '{family}';",
            f"  src: url('./assets/namefonts/{slug}.woff2') format('woff2');",
            '  font-display: swap;',
            '}',
            '',
        ]
    open(os.path.join(ROOT, 'src/namefonts.css'), 'w').write('\n'.join(css))

    ts = [
        '/**',
        ' * The fonts a display name can be lettered in.',
        ' *',
        " * Ids are the client's own DisplayNameFont enum. Generated by",
        ' * tools/fetch-name-fonts.py — edit that, not this. Neo Castel (7) and',
        ' * Sinistre (10) are missing because Discord licensed those two and no public',
        ' * mirror carries them; a lookalike would be worse than their absence.',
        ' */',
        '',
        'export type NameFont = { id: number; name: string; family: string }',
        '',
        'export const NAME_FONTS: NameFont[] = [',
        "  { id: 11, name: 'Default', family: 'inherit' },",
    ]
    for slug, (fid, _path, family) in FONTS.items():
        label = family
        ts.append(f"  {{ id: {fid}, name: '{label}', family: \"'{family}'\" }},")
    ts += [
        ']',
        '',
        'export const nameFontById = (id: number | undefined) =>',
        '  NAME_FONTS.find((f) => f.id === id) ?? NAME_FONTS[0]',
        '',
    ]
    open(os.path.join(ROOT, 'src/namefonts.ts'), 'w').write('\n'.join(ts))

    print(f'\n{len(FONTS)} faces, {total // 1024}KB total -> {OUT}')
    print('-> src/namefonts.css, src/namefonts.ts')


if __name__ == '__main__':
    main()
