"""
Builds the nameplate collection in src/nameplates.ts, with real flag artwork.

A nameplate is the strip Discord paints behind a member's name — the newest
kind of collectible, sold in the Shop beside the decorations. Its artwork lives
on `cdn.discordapp.com/assets/collectibles/nameplates/nameplates/<name>/`, which
this environment's egress policy denies, and no repo commits those files: the
two scrapers that handle nameplates (Safauri/nameplates,
Dev-Rick-C137/Discord-Shop-Assets) either fetch at runtime or park the results
on Google Drive, and the collectibles archives predate the feature entirely.

The country nameplates are the exception, because their artwork is a flag.
lipis/flag-icons (MIT) commits every flag as SVG, so those can be built for
real: the flag is rendered at the size the strip shows it, and the two colours
Discord would derive from the art are sampled the way the client samples them
(it reads the image and keeps its dominant colours as the nameplate's palette).

Only the four the Shop screenshot actually shows are emitted. The rest of
Discord's catalogue is real but its artwork is not reachable from here, and
guessing at names would be inventing a product line.

    python3 tools/fetch-nameplates.py
"""
import io
import os
import subprocess
import urllib.request
from collections import Counter

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'src/assets/nameplates')
OUT_TS = os.path.join(ROOT, 'src/nameplates.ts')

FLAGS = 'https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3'

# the four the Shop screenshot shows, with the price it shows on them
PLATES = [
    ('canada', 'Canada', 'ca'),
    ('france', 'France', 'fr'),
    ('norway', 'Norway', 'no'),
    ('scotland', 'Scotland', 'gb-sct'),
]
PRICE = 5.99
# the Shop here pays in the Orbs quests award rather than in money, on the same
# conversion src/ui/Decorations.tsx uses for a decoration's dollar price
ORBS = round(PRICE * 200 / 25) * 25

# the strip is drawn behind a row, so it is rendered wide and short
W, H = 320, 96


def render(svg: str, path: str) -> None:
    """Rasterises the flag with the browser, the way the other art tools do."""
    subprocess.run(
        ['node', os.path.join(ROOT, 'tools/rasterise.mjs'), path, str(W), str(H)],
        input=svg.encode(),
        check=True,
    )


def palette(im: Image.Image) -> list[str]:
    """
    The nameplate's two colours.

    Discord derives a nameplate's palette from its own artwork rather than
    storing one, so this does the same: quantise, drop the near-white and
    near-black that every flag has, and keep the two most common.
    """
    q = im.convert('RGB').resize((64, 48)).quantize(colors=8, method=Image.MEDIANCUT)
    pal = q.getpalette() or []
    counts = Counter(q.getdata())
    picked: list[str] = []
    for idx, _ in counts.most_common():
        r, g, b = pal[idx * 3 : idx * 3 + 3]
        if max(r, g, b) > 240 and min(r, g, b) > 220:
            continue
        if max(r, g, b) < 30:
            continue
        picked.append('#%02x%02x%02x' % (r, g, b))
        if len(picked) == 2:
            break
    while len(picked) < 2:
        picked.append('#4e5058')
    return picked


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    rows = []
    for slug, name, code in PLATES:
        with urllib.request.urlopen(f'{FLAGS}/{code}.svg', timeout=60) as r:
            svg = r.read().decode()
        png = os.path.join(OUT_DIR, f'{slug}.png')
        render(svg, png)
        im = Image.open(png)
        colors = palette(im)
        webp = os.path.join(OUT_DIR, f'{slug}.webp')
        im.convert('RGBA').save(webp, format='WEBP', quality=88, method=6)
        os.remove(png)
        rows.append((slug, name, colors))
        print(f'{slug:10} {code:7} {os.path.getsize(webp) // 1024:3}KB  {colors}')

    lines = [
        '/**',
        ' * Nameplates.',
        ' *',
        " * The strip Discord paints behind a member's name, and the newest thing the",
        ' * Shop sells. Generated by tools/fetch-nameplates.py — edit that, not this.',
        ' *',
        " * Only the country nameplates are here, because they are the only ones whose",
        ' * artwork is reachable: a flag is a flag, and lipis/flag-icons commits every',
        ' * one. The art-based nameplates Discord sells beside them live on its CDN,',
        ' * which is denied from this page. Each palette is sampled out of the artwork',
        " * the way the client samples it, rather than stored alongside.",
        ' */',
        '',
        "const art = import.meta.glob('./assets/nameplates/*.webp', {",
        '  eager: true,',
        "  query: '?url',",
        "  import: 'default',",
        '}) as Record<string, string>',
        '',
        'export type Nameplate = {',
        '  id: string',
        '  name: string',
        '  /** the two colours Discord would derive from the artwork */',
        '  palette: [string, string]',
        '  /** what Discord charges for it */',
        '  price: number',
        '  /** what it costs in Orbs here, on the Shop\'s own conversion */',
        '  orbs: number',
        '}',
        '',
        f'export const NAMEPLATES: Nameplate[] = [',
    ]
    for slug, name, colors in rows:
        lines.append(
            f"  {{ id: '{slug}', name: '{name}', palette: ['{colors[0]}', '{colors[1]}'],"
            f' price: {PRICE}, orbs: {ORBS} }},'
        )
    lines += [
        ']',
        '',
        'export const nameplateById = (id: string | undefined) =>',
        '  id == null ? undefined : NAMEPLATES.find((n) => n.id === id)',
        '',
        '/** The strip artwork for a nameplate, as a URL. */',
        "export const nameplateArt = (id: string) => art[`./assets/nameplates/${id}.webp`]",
        '',
    ]
    open(OUT_TS, 'w').write('\n'.join(lines))
    print(f'\n{len(rows)} nameplates -> {OUT_TS}')


if __name__ == '__main__':
    main()
