/**
 * Generates src/ui/DiscordIcons.tsx from the SVGs in
 * totallytavi/discord-app-icons (2023/tabs-v1) — Discord's own icon set.
 * Paths are copied byte-for-byte; only the <svg> wrapper is rebuilt so the
 * icons take their size and colour from CSS.
 */
import fs from 'node:fs'
import path from 'node:path'

const SRC = '/home/user/totallytavi/discord-app-icons/2023/tabs-v1'
const OUT = 'src/ui/DiscordIcons.tsx'

/** exported name -> source file */
const MAP = {
  HashIcon: 'textChannel',
  SpeakerIcon: 'voiceChannel',
  MegaphoneIcon: 'announcementChannel',
  ForumIcon: 'forums',
  RulesIcon: 'communityRules',
  StageIcon: 'stageChannel',
  EventsIcon: 'events',
  BrowseChannelsIcon: 'browseChannels',
  MembersIcon: 'membersChannel',
  BellIcon: 'notificationsChannel2',
  BellOffIcon: 'notificationsChannel',
  PinIcon: 'pinsChannel',
  ThreadsChannelIcon: 'threadsChannel',
  SearchIcon: 'search',
  InboxIcon: 'inbox',
  GearIcon: 'settings',
  MicIcon: 'mute',
  MicOffIcon: 'muteSelf',
  HeadphonesIcon: 'deafen',
  HeadphonesOffIcon: 'deafenSelf',
  AddMemberIcon: 'createInvite',
  BoostIcon: 'settingsBoost',
  ChannelCreateIcon: 'settingsChannelCreate',
  CaretIcon: 'caret',
  GiftIcon: 'gift',
  GifIcon: 'gif',
  StickerIcon: 'sticker',
  DownloadIcon: 'update',
  EditServerProfileIcon: 'settingsEditServerProfile',
}

const read = (name) => {
  const raw = fs.readFileSync(path.join(SRC, `${name}.svg`), 'utf8').trim()
  const viewBox = /viewBox="([^"]+)"/.exec(raw)?.[1] ?? '0 0 24 24'
  const inner = raw.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
  return { viewBox, inner }
}

let out = `/**
 * Discord's own icon set.
 *
 * Generated by tools/gen-icons.mjs from totallytavi/discord-app-icons
 * (2023/tabs-v1) — the paths are Discord's, copied verbatim; only the <svg>
 * wrapper is ours so each glyph inherits size and \`currentColor\` from CSS.
 * Re-run the generator rather than editing this file.
 */
import type { CSSProperties } from 'react'

type IconProps = {
  size?: number
  className?: string
  style?: CSSProperties
  title?: string
}

function make(viewBox: string, inner: string) {
  return function Icon({ size, className, style, title }: IconProps) {
    return (
      <svg
        viewBox={viewBox}
        width={size}
        height={size}
        className={className}
        style={style}
        role={title ? 'img' : undefined}
        aria-label={title}
        aria-hidden={title ? undefined : true}
        dangerouslySetInnerHTML={{ __html: inner }}
      />
    )
  }
}

`

for (const [name, file] of Object.entries(MAP)) {
  const { viewBox, inner } = read(file)
  out += `/** ${file}.svg */\nexport const ${name} = make(\n  '${viewBox}',\n  ${JSON.stringify(inner)},\n)\n\n`
}

fs.writeFileSync(OUT, out)
console.log(`wrote ${OUT} — ${Object.keys(MAP).length} icons`)
