/**
 * Builds src/emoji.ts from the catalogue + the downloaded Twemoji SVGs.
 *
 * Everything goes into one <symbol> sprite rather than 178 data URIs: the same
 * glyph is often used many times in a channel, and <use> costs a few bytes each
 * where a base64 data URI costs the whole file again.
 */
import fs from 'node:fs'
import { CATALOGUE } from './emoji-catalogue.mjs'

const SRC = 'src/assets/emoji'
const symbols = []
const rows = []

for (const [code, name, char, cat] of CATALOGUE) {
  const file = `${SRC}/${code}.svg`
  if (!fs.existsSync(file)) { console.log('skip (not downloaded):', name); continue }
  const raw = fs.readFileSync(file, 'utf8')
  const viewBox = /viewBox="([^"]+)"/.exec(raw)?.[1] ?? '0 0 36 36'
  const inner = raw.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  symbols.push(`<symbol id="e-${code}" viewBox="${viewBox}">${inner}</symbol>`)
  rows.push(`  { code: '${code}', name: '${name}', char: '${char}', cat: '${cat}' },`)
}

const out = `/**
 * Twemoji, the set Discord itself renders emoji with.
 *
 * Generated by tools/gen-emoji.mjs from jdecked/twemoji — edit
 * tools/emoji-catalogue.mjs and re-run rather than editing this file. Names are
 * Discord's shortcodes, so \`:joy:\` resolves the way it does in the real client.
 */
export type Emoji = { code: string; name: string; char: string; cat: string }

export const EMOJI: Emoji[] = [
${rows.join('\n')}
]

export const CATEGORIES: [string, string][] = [
  ['people', 'Smileys & People'],
  ['nature', 'Animals & Nature'],
  ['food', 'Food & Drink'],
  ['activities', 'Activities'],
  ['travel', 'Travel & Places'],
  ['objects', 'Objects'],
  ['symbols', 'Symbols'],
]

export const byName: Record<string, Emoji> = {}
export const byChar: Record<string, Emoji> = {}
for (const e of EMOJI) {
  byName[e.name] = e
  byChar[e.char] = e
  // some editors drop the variation selector; accept the bare form too
  if (e.char.length > 1) byChar[e.char.replace(/\\uFE0F$/, '')] = e
}

/** One sprite, injected once, referenced by every rendered glyph. */
export const SPRITE = ${JSON.stringify(
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">${symbols.join('')}</svg>`,
)}
`
fs.writeFileSync('src/emoji.ts', out)
console.log(`wrote src/emoji.ts — ${rows.length} emoji, sprite ${(symbols.join('').length / 1024).toFixed(0)}KB`)
