"""
Turns Discord's own spring configs into CSS easings.

Discord animates with react-spring, so its motion is not a duration and a
bezier — it is a damped harmonic oscillator, and every surface has its own
tension and friction. Those numbers are in the shipped bundle, and the ones
below are lifted from it verbatim (see docs/discord-reference.md for where each
one lives).

CSS cannot take a spring, but it can take `linear()`, which is an arbitrary
sampled curve. So this integrates each spring exactly the way react-spring's
frame loop does — 1ms Euler substeps, `springForce = -tension * 1e-6 * x`,
`dampingForce = -friction * 1e-3 * v`, both divided by mass — runs it until
react-spring itself would call it at rest, and emits the samples as a
`linear()` easing plus the duration it took. A transition using the pair moves
on Discord's curve rather than on an eyeballed approximation of it.

    python3 tools/gen-springs.py

Writes src/springs.css.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src/springs.css')

# name -> (tension, friction, mass, clamp, what it drives in Discord)
SPRINGS: dict[str, tuple[float, float, float, bool, str]] = {
    # Mana's modal/layer transition: scale(0.9) -> scale(1) with opacity, and a
    # 64ms delay before the enter. The exit runs on a different, stiffer spring.
    'modal-in': (1000, 48, 1, False, 'a modal or layer opening'),
    'modal-out': (1200, 80, 1, False, 'a modal or layer closing'),
    # the scrim behind a modal shares the enter spring
    'scrim': (1000, 48, 1, False, 'the dim behind a modal'),
    # tooltips and popouts: scale(0.95) -> scale(1) with opacity
    'popout': (2400, 52, 1, False, 'a tooltip or popout'),
    # the toast that slides up from the bottom
    'toast': (120, 14, 1, False, 'a toast arriving'),
    # the success toast Discord slides in with a 200ms delay
    'toast-success': (500, 18, 1, True, 'the success toast'),
    # a reaction pill popping when you add one
    'reaction': (450, 20, 1, True, 'a reaction landing'),
    # the panel that slides a settings section in and out
    'panel': (300, 28, 1, True, 'a settings section sliding'),
    # Discord's animated scroller, which is what Jump to Message rides
    'scroll': (200, 35, 2, True, 'a scroller jumping to a message'),
    # the quest entrypoint's shine and its glow
    'shine': (170, 38, 1, True, 'the quest tile shine'),
    'glow': (240, 12, 1, True, 'the quest tile glow'),
    # a button swapping what is inside it: the old contents shrink to 0.6 and
    # fade while the new ones come up
    'icon-swap': (700, 26, 1, False, "a button's contents changing"),
    # react-spring's own default, which is what Discord gets wherever it passes
    # no config at all — the notice bar sliding up from y:80, for one
    'default': (170, 26, 1, False, 'anything Discord leaves on the default'),
}

STEP = 1.0  # ms, react-spring's own substep


def solve(tension: float, friction: float, mass: float, clamp: bool) -> list[float]:
    """The spring's position, sampled every millisecond, from 0 to 1."""
    precision = 0.001  # react-spring's default for a 0..1 range
    x, v = 0.0, 0.0
    out = [0.0]
    for _ in range(4000):
        spring = -tension * 1e-6 * (x - 1.0)
        damping = -friction * 1e-3 * v
        v += (spring + damping) / mass * STEP
        x += v * STEP
        if clamp and x > 1.0:
            out.append(1.0)
            break
        out.append(x)
        if abs(v) <= precision and abs(1.0 - x) <= precision:
            break
    out[-1] = 1.0
    return out


def easing(samples: list[float], stops: int = 40) -> str:
    """The samples as a `linear()` easing, thinned to a readable number."""
    n = len(samples) - 1
    picked = [samples[round(i * n / stops)] for i in range(stops + 1)]
    picked[0], picked[-1] = 0.0, 1.0
    return 'linear(' + ', '.join(f'{p:.4f}'.rstrip('0').rstrip('.') or '0' for p in picked) + ')'


def main() -> None:
    lines = [
        '/*',
        ' * Discord\'s springs, as CSS easings. Generated by tools/gen-springs.py —',
        ' * edit that, not this.',
        ' *',
        ' * Each pair is one react-spring config out of Discord\'s own bundle, solved',
        ' * the way react-spring solves it and sampled into a `linear()` curve. Use',
        ' * them together: the duration is how long that spring actually takes to',
        ' * come to rest, and the easing is the shape it takes getting there.',
        ' */',
        '',
        ':root {',
    ]
    for name, (t, f, m, clamp, what) in SPRINGS.items():
        samples = solve(t, f, m, clamp)
        ms = len(samples) - 1
        lines.append(f'  /* {what} — tension {t:g}, friction {f:g}'
                     + (f', mass {m:g}' if m != 1 else '')
                     + (', clamped' if clamp else '') + ' */')
        lines.append(f'  --dur-{name}: {ms}ms;')
        lines.append(f'  --ease-{name}: {easing(samples)};')
    lines += ['}', '']
    open(OUT, 'w').write('\n'.join(lines))
    for name, (t, f, m, clamp, _) in SPRINGS.items():
        s = solve(t, f, m, clamp)
        print(f'{name:14} t{t:<5g} f{f:<4g} {len(s) - 1:4}ms  peak {max(s):.3f}')
    print(f'\n-> {OUT}')


if __name__ == '__main__':
    main()
