import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(500)
await p.click('[aria-label="User settings"]')
await p.waitForSelector('.settings-layer', { timeout: 3000 })
await p.click('.settings-item:has-text("Connections")')
await p.waitForTimeout(250)
await p.click('.conn-tile[aria-label="Spotify"]')
await p.fill('#conn-handle', 'nebula')
await p.click('.conn-add-row .btn-primary')
await p.waitForTimeout(150)
await p.click('.conn-tile[aria-label="Steam"]')
await p.fill('#conn-handle', 'nebula_')
await p.click('.conn-add-row .btn-primary')
await p.waitForTimeout(300)
await p.screenshot({ path: process.argv[2] })
await b.close()
