import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 950 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
await p.addInitScript(() => localStorage.setItem('discord-ui:v4:orbs', '9800'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(600)
await p.click('.dm-nav .row:has-text("Shop")').catch(async () => {
  await p.click('.server-tile.home, [aria-label="Direct Messages"]')
  await p.click('.dm-nav .row:has-text("Shop")')
})
await p.waitForTimeout(400)
await p.click('.shop-tab:has-text("Nameplates")')
await p.waitForTimeout(500)
await p.screenshot({ path: process.argv[2] })
// buy and wear one with real art
await p.fill('.plate-filter', 'cityscape')
await p.waitForTimeout(300)
const card = p.locator('.shop-item:has-text("Cityscape")')
await card.locator('.shop-buy').click()
await p.waitForTimeout(200)
await card.locator('.shop-buy').click()
await p.waitForTimeout(300)
await p.click('.server-tile.srv')
await p.waitForTimeout(400)
if (await p.locator('.age-gate').count()) await p.click('.age-gate .btn-primary')
await p.click('[aria-label="Toggle member list"]')
await p.waitForTimeout(400)
await p.screenshot({ path: process.argv[3] })
await b.close()
