import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(600)
await p.click('.composer-input')
await p.fill('.composer-input', 'click my avatar')
await p.press('.composer-input', 'Enter')
await p.waitForTimeout(300)
await p.click('button.group-avatar >> nth=-1')
await p.waitForSelector('.popout.anchored', { timeout: 3000 })
await p.waitForTimeout(400)
await p.screenshot({ path: process.argv[2] })
// and from the member list
await p.keyboard.press('Escape')
await p.waitForTimeout(200)
await p.click('[aria-label="Show Member List"], [aria-label="Members"], .chat-actions button:last-child').catch(() => {})
await p.waitForTimeout(300)
const members = await p.locator('.member').count()
if (members) {
  await p.click('.member')
  await p.waitForSelector('.popout.anchored', { timeout: 3000 })
  await p.waitForTimeout(300)
  await p.screenshot({ path: process.argv[3] })
  await p.click('.popout .p-btn:has-text("View Full Profile")')
  await p.waitForTimeout(400)
  await p.screenshot({ path: process.argv[4] })
} else console.log('no member list open')
await b.close()
