import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(600)
await p.click('[aria-label="Edit channel"] >> nth=0', { force: true })
await p.waitForSelector('.settings-layer', { timeout: 4000 })
await p.click('.set-row:has-text("Age-Restricted") .switch, .switch >> nth=0')
await p.waitForTimeout(200)
await p.keyboard.press('Escape')
await p.waitForTimeout(500)
await p.screenshot({ path: process.argv[2] })
await p.click('.age-gate .btn-primary')
await p.waitForTimeout(300)
await p.screenshot({ path: process.argv[3] })
await b.close()
