import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const out = process.argv[2]
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
p.on('pageerror', (e) => console.log('pageerror:', String(e).split('\n')[0]))
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(500)
await p.click('.rail-home, .server-tile.home, [aria-label="Direct Messages"]').catch(() => {})
await p.waitForTimeout(300)
await p.click('.dm-nav .row:has-text("Shop")')
await p.waitForTimeout(400)
await p.click('.shop-tab:has-text("Browse")')
await p.waitForTimeout(300)
await p.screenshot({ path: `${out}/shop-browse.png` })
await p.click('.shop-tile:has-text("Monsters")')
await p.waitForTimeout(500)
await p.screenshot({ path: `${out}/shop-collection.png` })
await p.evaluate(() => document.querySelector('.shop-body').scrollTo(0, 900))
await p.waitForTimeout(300)
await p.screenshot({ path: `${out}/shop-collection2.png` })
await b.close()
