import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(700)
await p.click('.server-tile.srv')
await p.waitForTimeout(400)
// send a GIF, then star it from the message
await p.setInputFiles('.composer-wrap input[type=file]', '/tmp/fav.gif')
await p.waitForTimeout(300)
await p.click('.composer-input')
await p.press('.composer-input', 'Enter')
await p.waitForTimeout(400)
await p.hover('.attachment')
await p.waitForTimeout(200)
await p.screenshot({ path: process.argv[2] })
await p.click('.attachment-fav')
await p.waitForTimeout(300)
// the favourite is now in the picker
await p.click('[aria-label="GIF"]')
await p.waitForSelector('.picker-gif', { timeout: 3000 })
await p.waitForTimeout(300)
await p.screenshot({ path: process.argv[3] })
await p.click('.picker-gif')
await p.waitForTimeout(400)
console.log('gif attachments:', await p.locator('.attachment').count())
await b.close()
