import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
// plenty of Orbs so the plates can actually be bought
await p.addInitScript(() => localStorage.setItem('discord-ui:v4:orbs', '9800'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(600)
await p.click('.dm-nav .row:has-text("Shop")').catch(async () => {
  await p.click('.server-tile.home, [aria-label="Direct Messages"]')
  await p.click('.dm-nav .row:has-text("Shop")')
})
await p.waitForTimeout(500)
await p.fill('.shop-search input', 'norway')
await p.waitForTimeout(400)
await p.screenshot({ path: process.argv[2] })
const buy = p.locator('.shop-item:has-text("Norway") .shop-buy')
console.log('buy label:', await buy.innerText().catch(() => 'none'))
await buy.click()
await p.waitForTimeout(300)
await p.locator('.shop-item:has-text("Norway") .shop-buy').click()
await p.waitForTimeout(300)
await p.screenshot({ path: process.argv[3] })
// now open the member list and look at the row
await p.keyboard.press('Escape')
await p.click('.server-tile.srv')
await p.waitForTimeout(400)
await p.click('[aria-label="Toggle member list"]')
await p.waitForTimeout(400)
console.log('members:', await p.locator('.member').count())
await p.screenshot({ path: process.argv[4] })
await b.close()
