import { chromium } from 'playwright'
import { readFileSync } from 'node:fs'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const p = await b.newPage({ viewport: { width: 1558, height: 900 } })
await p.addInitScript(readFileSync('tools/session.js', 'utf8'))
p.on('pageerror', (e) => console.log('ERR', String(e).split('\n')[0]))
await p.goto('file://' + process.cwd() + '/dist/index.html')
await p.waitForTimeout(700)
await p.click('.server-tile.srv')
await p.waitForTimeout(400)
await p.click('[aria-label="GIF"]')
await p.waitForSelector('.picker-gif', { timeout: 3000 })
console.log('library gifs:', await p.locator('.picker-gif').count())
await p.fill('.picker-search input', 'party')
await p.waitForTimeout(300)
console.log('after search "party":', await p.locator('.picker-gif').count())
await p.screenshot({ path: process.argv[2] })
await p.click('.picker-gif')
await p.waitForTimeout(400)
console.log('sent:', await p.locator('.attachment-gif').count())
await p.screenshot({ path: process.argv[3] })
await b.close()
