/**
 * The GIF library behind the picker.
 *
 * Discord's GIF tab is a Tenor search: its API needs a key this build has no
 * way to hold and its media host is denied here, so that is closed. These are
 * Google's Noto Animated Emoji instead — real animated GIFs, served from
 * fonts.gstatic.com, licensed CC BY 4.0, and exactly the kind of thing people
 * react with. Generated by tools/fetch-gifs.py — edit that, not this.
 */

const art = import.meta.glob('./assets/gifs/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

export type LibraryGif = {
  id: string
  name: string
  /** what a search over the library matches on */
  tags: string
  category: string
}

export const GIF_CATEGORIES = [
  'Reactions',
  'Love',
  'Celebrate',
  'Feelings',
  'Mood',
  'Things',
]

export const GIFS: LibraryGif[] = [
  { id: '1f602', name: 'Tears of Joy', tags: 'lol laugh funny cry', category: 'Reactions' },
  { id: '1f923', name: 'Rolling on the Floor', tags: 'rofl lol laugh dying', category: 'Reactions' },
  { id: '1f44d', name: 'Thumbs Up', tags: 'yes ok good agree', category: 'Reactions' },
  { id: '1f44e', name: 'Thumbs Down', tags: 'no bad disagree', category: 'Reactions' },
  { id: '1f440', name: 'Eyes', tags: 'look watching sus', category: 'Reactions' },
  { id: '1f914', name: 'Thinking', tags: 'hmm think consider', category: 'Reactions' },
  { id: '1f644', name: 'Rolling Eyes', tags: 'ugh whatever annoyed', category: 'Reactions' },
  { id: '1f612', name: 'Unamused', tags: 'meh bored done', category: 'Reactions' },
  { id: '1f92f', name: 'Mind Blown', tags: 'wow shocked exploding', category: 'Reactions' },
  { id: '1f480', name: 'Skull', tags: 'dead dying lol', category: 'Reactions' },
  { id: '1f60d', name: 'Heart Eyes', tags: 'love adore crush', category: 'Love' },
  { id: '2764_fe0f', name: 'Red Heart', tags: 'love heart', category: 'Love' },
  { id: '1f496', name: 'Sparkling Heart', tags: 'love cute sparkle', category: 'Love' },
  { id: '1f494', name: 'Broken Heart', tags: 'sad heartbreak', category: 'Love' },
  { id: '1f97a', name: 'Pleading', tags: 'please cute puppy eyes', category: 'Love' },
  { id: '1f63b', name: 'Heart Eyes Cat', tags: 'love cat', category: 'Love' },
  { id: '1f389', name: 'Party Popper', tags: 'party celebrate congrats', category: 'Celebrate' },
  { id: '1f973', name: 'Partying Face', tags: 'party celebrate birthday', category: 'Celebrate' },
  { id: '1f44f', name: 'Clap', tags: 'applause well done', category: 'Celebrate' },
  { id: '1f4af', name: 'Hundred', tags: '100 perfect score', category: 'Celebrate' },
  { id: '2728', name: 'Sparkles', tags: 'shiny magic clean', category: 'Celebrate' },
  { id: '1f680', name: 'Rocket', tags: 'launch fast ship it', category: 'Celebrate' },
  { id: '1f62d', name: 'Sobbing', tags: 'cry sad tears', category: 'Feelings' },
  { id: '1f621', name: 'Rage', tags: 'angry mad furious', category: 'Feelings' },
  { id: '1f631', name: 'Screaming', tags: 'shock horror scared', category: 'Feelings' },
  { id: '1f634', name: 'Sleeping', tags: 'tired sleep zzz', category: 'Feelings' },
  { id: '1f971', name: 'Yawning', tags: 'tired bored sleepy', category: 'Feelings' },
  { id: '1f64f', name: 'Folded Hands', tags: 'please thanks pray', category: 'Feelings' },
  { id: '1f60e', name: 'Sunglasses', tags: 'cool deal with it', category: 'Mood' },
  { id: '1f60f', name: 'Smirk', tags: 'smug sly', category: 'Mood' },
  { id: '1f525', name: 'Fire', tags: 'lit hot flame', category: 'Mood' },
  { id: '26a1', name: 'High Voltage', tags: 'fast lightning zap', category: 'Mood' },
  { id: '1f608', name: 'Smiling Imp', tags: 'evil devil mischief', category: 'Mood' },
  { id: '1f47b', name: 'Ghost', tags: 'boo spooky', category: 'Mood' },
  { id: '1f916', name: 'Robot', tags: 'bot beep boop', category: 'Things' },
  { id: '1f9e0', name: 'Brain', tags: 'smart think galaxy', category: 'Things' },
  { id: '1f984', name: 'Unicorn', tags: 'magic rare', category: 'Things' },
  { id: '1f355', name: 'Pizza', tags: 'food hungry', category: 'Things' },
  { id: '1f382', name: 'Birthday Cake', tags: 'birthday cake party', category: 'Things' },
  { id: '1f9cb', name: 'Bubble Tea', tags: 'boba drink', category: 'Things' },
]

/** The animation for a library GIF, as a URL. */
export const gifArt = (id: string) => art[`./assets/gifs/${id}.webp`]
