/**
 * Nameplates.
 *
 * The strip Discord paints behind a member's name, and the newest thing the
 * Shop sells. Generated by tools/fetch-nameplates.py — edit that, not this.
 *
 * Only the country nameplates are here, because they are the only ones whose
 * artwork is reachable: a flag is a flag, and lipis/flag-icons commits every
 * one. The art-based nameplates Discord sells beside them live on its CDN,
 * which is denied from this page. Each palette is sampled out of the artwork
 * the way the client samples it, rather than stored alongside.
 */

const art = import.meta.glob('./assets/nameplates/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

export type Nameplate = {
  id: string
  name: string
  /** the two colours Discord would derive from the artwork */
  palette: [string, string]
  /** what Discord charges for it */
  price: number
  /** what it costs in Orbs here, on the Shop's own conversion */
  orbs: number
}

export const NAMEPLATES: Nameplate[] = [
  { id: 'canada', name: 'Canada', palette: ['#d52b1e', '#d52a1d'], price: 5.99, orbs: 1200 },
  { id: 'france', name: 'France', palette: ['#000092', '#e1000f'], price: 5.99, orbs: 1200 },
  { id: 'norway', name: 'Norway', palette: ['#ed2939', '#002260'], price: 5.99, orbs: 1200 },
  { id: 'scotland', name: 'Scotland', palette: ['#0065bd', '#0061bb'], price: 5.99, orbs: 1200 },
]

export const nameplateById = (id: string | undefined) =>
  id == null ? undefined : NAMEPLATES.find((n) => n.id === id)

/** The strip artwork for a nameplate, as a URL. */
export const nameplateArt = (id: string) => art[`./assets/nameplates/${id}.webp`]

/**
 * The wash Discord lays under the artwork.
 *
 * The client derives a nameplate's gradient from the artwork's own colours and
 * runs it left to right under the row, with the art itself sitting at the
 * trailing edge and fading out.
 */
export const nameplateWash = (n: Nameplate) =>
  `linear-gradient(to right, transparent 0%, ${n.palette[0]}33 45%, ${n.palette[1]}66 100%)`
