/**
 * The fonts a display name can be lettered in.
 *
 * Ids are the client's own DisplayNameFont enum. Generated by
 * tools/fetch-name-fonts.py — edit that, not this. Neo Castel (7) and
 * Sinistre (10) are missing because Discord licensed those two and no public
 * mirror carries them; a lookalike would be worse than their absence.
 */

export type NameFont = { id: number; name: string; family: string }

export const NAME_FONTS: NameFont[] = [
  { id: 11, name: 'Default', family: 'inherit' },
  { id: 3, name: 'Cherry Bomb One', family: "'Cherry Bomb One'" },
  { id: 4, name: 'Chicle', family: "'Chicle'" },
  { id: 6, name: 'MuseoModerno', family: "'MuseoModerno'" },
  { id: 8, name: 'Pixelify Sans', family: "'Pixelify Sans'" },
  { id: 12, name: 'Zilla Slab', family: "'Zilla Slab'" },
  { id: 13, name: 'Playpen Sans', family: "'Playpen Sans'" },
  { id: 14, name: 'Orbitron', family: "'Orbitron'" },
  { id: 15, name: 'New Rocker', family: "'New Rocker'" },
  { id: 16, name: 'Kalam', family: "'Kalam'" },
]

export const nameFontById = (id: number | undefined) =>
  NAME_FONTS.find((f) => f.id === id) ?? NAME_FONTS[0]
