/**
 * The Shop's catalogue — Discord's own.
 *
 * Generated by tools/fetch-shop.py from Infinitay/discord-collectibles-archive,
 * which keeps Discord's collectibles catalogue committed as JSON. The
 * collection names and summaries, the bundle and item names, the gradient
 * colours and both prices — what Discord charges, and the lower price it
 * charges a Nitro subscriber — are all theirs.
 *
 * Only the collections whose avatar decorations are vendored under
 * src/assets/decorations are here, so nothing on the page is a name without
 * art behind it. Profile effects are listed with their real names but have no
 * artwork: those are rendered from Discord's CDN, which is unreachable here.
 *
 * Do not edit — run the tool.
 */

export type ShopProduct = {
  id: string
  name: string
  summary: string
  /** USD, as Discord lists it */
  price: number | null
  /** USD, the reduced price a Nitro subscriber pays */
  nitro: number | null
  /** bundles only: the products inside */
  items?: string[]
}

export type ShopCollection = {
  id: string
  name: string
  summary: string
  /** the collection's own gradient, from Discord's style block */
  colors: string[]
  button: string
  bundles: ShopProduct[]
  decorations: ShopProduct[]
  effects: ShopProduct[]
}

export const COLLECTIONS: ShopCollection[] = [
  {
    "id": "elements",
    "name": "Elements",
    "summary": "Which will you unleash?",
    "colors": [
      "#1b1ba1",
      "#001629"
    ],
    "button": "#ebbd1a",
    "bundles": [
      {
        "id": "elemental-bundle",
        "name": "Elemental Bundle",
        "summary": "A bundle of collectibles.",
        "price": 10.99,
        "nitro": 8.99,
        "items": [
          "Balance",
          "Mastery"
        ]
      }
    ],
    "decorations": [
      {
        "id": "fire",
        "name": "Fire",
        "summary": "Ignite your flame within.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "water",
        "name": "Water",
        "summary": "Control the ebb and flow.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "air",
        "name": "Air",
        "summary": "Will the wind.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "earth",
        "name": "Earth",
        "summary": "Call the might of the earth.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "lightning",
        "name": "Lightning",
        "summary": "Electrify your presence.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "balance",
        "name": "Balance",
        "summary": "Harness the elements.",
        "price": 5.99,
        "nitro": 4.99
      }
    ],
    "effects": [
      {
        "id": "rock-slide",
        "name": "Rock Slide",
        "summary": "A ballet of rock and stone.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "vortex",
        "name": "Vortex",
        "summary": "Beware the eye of the storm.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "mastery",
        "name": "Mastery",
        "summary": "Unleash the elements.",
        "price": 5.99,
        "nitro": 4.99
      }
    ]
  },
  {
    "id": "galaxy",
    "name": "Galaxy",
    "summary": "Reach for the stars.",
    "colors": [
      "#111214",
      "#111214"
    ],
    "button": "#5865f2",
    "bundles": [
      {
        "id": "stargazing-bundle",
        "name": "Stargazing Bundle",
        "summary": "A bundle of collectibles.",
        "price": 10.99,
        "nitro": 8.99,
        "items": [
          "Constellations",
          "Twilight"
        ]
      }
    ],
    "decorations": [
      {
        "id": "stardust",
        "name": "Stardust",
        "summary": "The essence of the cosmos.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "black-hole",
        "name": "Black Hole",
        "summary": "An enigma of matter, space, and time.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "constellations",
        "name": "Constellations",
        "summary": "What secrets do the stars reveal?",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "solar-orbit",
        "name": "Solar Orbit",
        "summary": "An eternal dance of fiery passion.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "ufo",
        "name": "UFO",
        "summary": "The perfect ride for any grab-and-go heist.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "astronaut-helmet",
        "name": "Astronaut Helmet",
        "summary": "Always wear your helmet.",
        "price": 5.99,
        "nitro": 4.99
      }
    ],
    "effects": [
      {
        "id": "shooting-stars",
        "name": "Shooting Stars",
        "summary": "May your wish come true.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "supernova",
        "name": "Supernova",
        "summary": "Light up the cosmos.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "twilight",
        "name": "Twilight",
        "summary": "Is the universe winking at me?",
        "price": 5.99,
        "nitro": 4.99
      }
    ]
  },
  {
    "id": "lofi-vibes",
    "name": "Lofi Vibes",
    "summary": "Where chill meets mood.",
    "colors": [
      "#635dff",
      "#df82b9"
    ],
    "button": "#5865f2",
    "bundles": [
      {
        "id": "cozy-plant-vibes-bundle",
        "name": "Cozy Plant Vibes Bundle",
        "summary": "A bundle of collectibles.",
        "price": 10.99,
        "nitro": 8.99,
        "items": [
          "Oasis",
          "All Nighter"
        ]
      }
    ],
    "decorations": [
      {
        "id": "chromawave",
        "name": "Chromawave",
        "summary": "Never miss a beat.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "cozy-cat",
        "name": "Cozy Cat",
        "summary": "Vibing one catnap at a time.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "oasis",
        "name": "Oasis",
        "summary": "Chilling in my comfort place.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "rainy-mood",
        "name": "Rainy Mood",
        "summary": "Feel the calm.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "cozy-headphones",
        "name": "Cozy Headphones",
        "summary": "Perfect for any tune.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "doodling",
        "name": "Doodling",
        "summary": "What do you mean I'm procrastinating?",
        "price": 5.99,
        "nitro": 4.99
      }
    ],
    "effects": [
      {
        "id": "study-spot",
        "name": "Study Spot",
        "summary": "Time to hit the books.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "all-nighter",
        "name": "All Nighter",
        "summary": "Wait, it's already morning?",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "watercolors",
        "name": "Watercolors",
        "summary": "When the world feels grey, add a splash of color.",
        "price": 5.99,
        "nitro": 4.99
      }
    ]
  },
  {
    "id": "lunar-new-year",
    "name": "Lunar New Year",
    "summary": "Roar into the Year of the Dragon.",
    "colors": [
      "#8d0000",
      "#5b0000"
    ],
    "button": "#ffb106",
    "bundles": [],
    "decorations": [
      {
        "id": "fan-flourish",
        "name": "Fan Flourish",
        "summary": "Incredibly fan-tastic.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "lunar-lanterns",
        "name": "Lunar Lanterns",
        "summary": "Light the night.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "firecrackers",
        "name": "Firecrackers",
        "summary": "Don't try this at home!",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "dragons-smile",
        "name": "Dragon's Smile",
        "summary": "A dragon's grin fills your year with laughs.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "lucky-envelopes",
        "name": "Lucky Envelopes",
        "summary": "Capacity: 888 coins.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "koi-pond",
        "name": "Koi Pond",
        "summary": "Swimming in an eternal, peaceful circle.",
        "price": 5.99,
        "nitro": 4.99
      }
    ],
    "effects": [
      {
        "id": "dragon-dance",
        "name": "Dragon Dance",
        "summary": "No evil spirits on my watch.",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "fortune-flurry",
        "name": "Fortune Flurry",
        "summary": "May fortune come your way!",
        "price": 5.99,
        "nitro": 4.99
      },
      {
        "id": "midnight-celebration",
        "name": "Midnight Celebration",
        "summary": "Protection and prosperity guaranteed.",
        "price": 5.99,
        "nitro": 4.99
      }
    ]
  }
]

export const money = (n: number) => `$${n.toFixed(2)}`
